version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 50
  target-branch: updates
  milestone: 1
  assignees:
  - "bengosney"
  allow:
  - dependency-type: direct
  - dependency-type: indirect
