[project]
name = "Is It Bin Day"
version = "0.1.3"
description = "More usefull task list"
authors = ["Ben Gosney <bengosney@googlemail.com>"]
python = "^3.8"
homepage = "https://www.isitbinday.com/"
repository = "https://github.com/bengosney/isitbinday/"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 128
target-version = ['py37']

[tool.pycln]
all = true
