[project]
name = "is-it-bin-day"
version = "0.1.3"
description = "More useful task list"
authors = [
  {email = "bengosney@googlemail.com", name = "Ben Gosney"}
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 128
target-version = ['py310']

[tool.pycln]
all = true
