# Generated by Django 3.1.6 on 2021-04-03 18:41

from typing import List, Tuple
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies:List[Tuple[str, str]] = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_pages', models.IntegerField()),
                ('publish_date', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(max_length=30)),
                ('authors', models.ManyToManyField(to='books.author')),
            ],
        ),
    ]
