# Generated by Django 3.1.6 on 2021-04-04 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_auto_20210404_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='barcode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'barcode'), ('title', 'owner'), ('isbn', 'owner')},
        ),
    ]
