# Generated by Django 3.1.6 on 2021-04-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210404_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.Author'),
        ),
    ]
