# Generated by Django 3.2.4 on 2021-08-03 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_auto_20210405_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.Author'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'owner'), ('title', 'owner')},
        ),
        migrations.RemoveField(
            model_name='book',
            name='barcode',
        ),
    ]
