# Generated by Django 3.2.4 on 2021-08-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_authors'),
        ('books', '0007_auto_20210803_0751'),
    ]

    operations = [
    ]
