# Generated by Django 3.2.4 on 2021-08-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_merge_0007_alter_book_authors_0007_auto_20210803_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.Author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
