# Generated by Django 3.2.9 on 2021-11-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20211113_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='requires_refetch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.Author'),
        ),
    ]
