# Generated by Django 5.0.6 on 2024-05-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20211113_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tmp_cover',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
