# Generated by Django 5.1 on 2024-08-14 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_syncsetting_syncmetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncmetadata',
            name='_rev',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='syncmetadata',
            name='book',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_metadata', to='books.book'),
        ),
    ]
