# Generated by Django 5.1 on 2024-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_syncmetadata__rev_alter_syncmetadata_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
