# Generated by Django 5.1 on 2024-08-17 13:26

import django_cryptography.fields
from django.db import migrations, models


def copy_old_password_to_password(apps, schema_editor):
    SyncSetting = apps.get_model('books', 'SyncSetting')
    for setting in SyncSetting.objects.all():
        setting.password = setting.old_password
        setting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syncsetting',
            old_name='password',
            new_name='old_password',
        ),
        migrations.AddField(
            model_name='syncsetting',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(default='not set', max_length=255)),
            preserve_default=False,
        ),
        migrations.RunPython(copy_old_password_to_password),
        migrations.RemoveField(
            model_name='syncsetting',
            name='old_password',
        ),
    ]
