version: 2.1
orbs:
  python: circleci/python@3.0.0

jobs:
  test:
    docker:
    # [[[cog
    # import cog
    # with open(".python-version") as f:
    #   cog.out(f"- image: cimg/python:{f.read().strip()}")
    # ]]]
    - image: cimg/python:3.12
    # [[[end]]]
    steps:
    - checkout
    - restore_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}
    - python/install-packages:
        pip-dependency-file: requirements.dev.txt
        pkg-manager: pip
    - save_cache:
        key: v3-deps-{{ checksum "requirements.dev.txt" }}
        paths:
        - /home/circleci/.local/share/virtualenvs
        - /home/circleci/.cache/pip
    - run:
        name: Run tests
        command: DJANGO_SETTINGS_MODULE=stl.settings.dev python -m pytest
    - run:
        name: Django system check
        command: DJANGO_SETTINGS_MODULE=stl.settings.dev python manage.py check

workflows:
  tests:
    jobs:
    - test
