version: 2.1
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
        environment:
          DATABASE_URL: postgresql://postgres:password@localhost:5432/circle_test?sslmode=disable
          ENV: testing
      - image: circleci/postgres:12.9
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password

    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "requirements.dev.txt" }}
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: install dependencies
          command: pipenv install --dev -r requirements.dev.txt
      - save_cache:
          key: v1-deps-{{ checksum "requirements.dev.txt" }}
          paths:
            - /home/circleci/.local/share/virtualenvs
      - run:
          name: Run tests
          command: pipenv run ./manage.py test
