# Generated by Django 4.0.4 on 2022-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='difficulty',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
