# Generated by Django 4.0.4 on 2022-04-19 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiit', '0004_workout_interval_workout_round_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='round_length',
            field=models.DurationField(default=datetime.timedelta(seconds=45)),
        ),
    ]
