# Generated by Django 4.0.4 on 2022-04-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiit', '0005_alter_workout_round_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='hiit.exercise'),
        ),
    ]
