# Generated by Django 6.0 on 2025-12-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_homegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homegroup',
            name='Admin',
        ),
    ]
