# Generated by Django 3.1 on 2020-08-19 07:57

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Due Date')),
                ('effort', models.IntegerField(default=0, verbose_name='Effort')),
                ('state', django_fsm.FSMField(choices=[('draft', 'draft'), ('todo', 'todo'), ('doing', 'doing'), ('done', 'done'), ('canceled', 'canceled')], default='todo', max_length=50, protected=True, verbose_name='State')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
        ),
    ]
