# Generated by Django 3.1 on 2020-08-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='tasks',
            field=models.ManyToManyField(to='tasks.Task'),
        ),
    ]
