# Generated by Django 3.1 on 2020-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20200820_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='finished',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Finished'),
        ),
    ]
