# Generated by Django 3.1 on 2020-08-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_blocked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='blocked_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
