# Generated by Django 3.1 on 2020-08-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200824_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocks', to='tasks.task'),
        ),
    ]
