# Generated by Django 3.1 on 2020-10-19 07:32

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20200914_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed on'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeats',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Repeats'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done'), ('canceled', 'canceled'), ('archive', 'archive')], default='todo', max_length=50, protected=True, verbose_name='State'),
        ),
    ]
