# Generated by Django 3.1 on 2020-10-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20201019_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_after',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Show After'),
        ),
    ]
