# Generated by Django 3.1 on 2020-10-21 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_show_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='show_after',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Show After'),
            preserve_default=False,
        ),
    ]
