# Generated by Django 3.1 on 2020-11-16 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20201021_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='show_after',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Show After'),
        ),
    ]
