# Generated by Django 5.1 on 2024-08-10 14:35

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_auto_20201116_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived',
            field=django_fsm.FSMField(choices=[('active', 'active'), ('archived', 'archived')], default='active', max_length=50, protected=True, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=django_fsm.FSMField(choices=[('todo', 'todo'), ('doing', 'doing'), ('done', 'done'), ('canceled', 'canceled')], default='todo', max_length=50, protected=True, verbose_name='State'),
        ),
        migrations.RunSQL(
            "UPDATE tasks_task SET archived = 'archived' WHERE state = 'archive';"
        ),
    ]
