# Generated by Django 3.2.6 on 2021-08-30 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User

def getDefaultUser():
    user = User.objects.filter(is_staff=True, is_active=True).first()
    if user is not None:
        return user.id
    
    raise Exception("No active staff member found")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_auto_20210829_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='owner',
            field=models.ForeignKey(default=getDefaultUser(), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(default=getDefaultUser(), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='owner',
            field=models.ForeignKey(default=getDefaultUser(), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(default=getDefaultUser(), on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.unit'),
        ),
    ]
