# Generated by Django 3.2.6 on 2021-08-30 18:52

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210830_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'owner']),
        ),
    ]
