# Generated by Django 3.2.6 on 2021-08-31 19:57

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default='', max_length=512, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='link',
            field=models.URLField(blank=True, default='', verbose_name='Original URL'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('name',), verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.DurationField(default=0, verbose_name='Time to cook'),
        ),
    ]
