# Generated by Django 4.1.2 on 2022-10-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20210831_1957"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
