# Generated by Django 4.1.2 on 2022-10-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_ingredient_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=30, unique=False),
        ),
    ]
