# Generated by Django 4.1.2 on 2022-10-08 20:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_alter_unit_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="ingredient",
            unique_together={("owner", "name", "recipe")},
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("owner", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together={("owner", "description", "recipe")},
        ),
        migrations.AlterUniqueTogether(
            name="unit",
            unique_together={("owner", "name")},
        ),
    ]
