# Generated by Django 3.1 on 2020-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201120_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('Room Temperature', 'Room Temperature'), ('Fridge', 'Fridge'), ('Freezer', 'Freezer')], max_length=30),
        ),
    ]
