# Generated by Django 3.1 on 2020-11-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20201121_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='can_move_to',
            field=models.BooleanField(default=True),
        ),
    ]
