# Generated by Django 3.1 on 2020-11-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_location_can_move_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
