# Generated by Django 3.1 on 2020-11-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20201121_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='temperature',
            field=models.CharField(choices=[('Room Temperature', 'Room Temperature'), ('Chilled', 'Chilled'), ('Frozen', 'Frozen')], default='Room Temperature', max_length=50),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_from', to='food.stock')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferred_to', to='food.stock')),
            ],
        ),
    ]
