# Generated by Django 3.1 on 2020-11-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20201122_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='temperature',
            field=models.CharField(blank=True, choices=[('Room Temperature', 'Room Temperature'), ('Chilled', 'Chilled'), ('Frozen', 'Frozen')], default='Room Temperature', max_length=50, null=True),
        ),
    ]
