# Generated by Django 3.1 on 2020-11-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20201122_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
