# Generated by Django 3.1 on 2020-11-26 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0014_auto_20201126_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='auth.user'),
            preserve_default=False,
        ),
    ]
