# Generated by Django 3.1.3 on 2020-11-30 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0015_stock_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='auth.user'),
            preserve_default=False,
        ),
    ]
