# Generated by Django 3.1.4 on 2021-01-10 09:11

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_transfer_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='state_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='state'),
        ),
        migrations.AddField(
            model_name='stock',
            name='temperature_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='temperature'),
        ),
    ]
