---
name: "deploy"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix known_hosts for git.flaminghedgehog.com
        run: |
          ssh-keygen -R git.flaminghedgehog.com -f ~/.ssh/known_hosts || true
          ssh-keyscan git.flaminghedgehog.com >> ~/.ssh/known_hosts

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
          git_remote_url: ${{ secrets.SSH_HOST_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
