# Generated by Django 3.1.4 on 2020-12-30 20:24

from django.conf import settings
from django.db import migrations

def create_auth_models(apps, schema_editor):
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    AuthDetails = apps.get_model('userauth', 'AuthDetails')
    for user in User.objects.all():
        try:
            has_auth = (user.authdetails is not None)
        except AuthDetails.DoesNotExist:
            AuthDetails.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20201230_2017'),
    ]

    operations = [
        migrations.RunPython(create_auth_models),
    ]
