# Generated by Django 3.1.4 on 2021-01-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_auto_20201230_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authdetails',
            name='homeGroups',
            field=models.ManyToManyField(related_name='userprofiles', to='userauth.HomeGroup'),
        ),
    ]
